
#+BEGIN_SRC emacs-lisp
(org-link-set-parameters
 "github-issue"
 :follow (lambda (path)
	   (browse-url
	    (format "https://github.com/jkitchin/org-ref/issues/%s" path))))
#+END_SRC

#+RESULTS:

* 381 Testing labels

label:test.1

label:test-1 \label{fig:test-foo} \label{fig:testfoo}

ref:test.1  ref:test  ref:test-1

<2017-02-22 Wed>

I found some minor inconsistencies with labels and ref messages that are caused by allowing . in the name. The . in particular is tricky since it is a special regexp character. I added regexp-quote in a lot of places to accommodate this.


#+BEGIN_SRC emacs-lisp
(org-ref-get-labels)
#+END_SRC

#+RESULTS:
| test.1 | test-1 | fig:test-foo | fig:testfoo |

#+BEGIN_SRC emacs-lisp
(org-ref-count-labels "test")
#+END_SRC

#+RESULTS:
: 0

* 388 

https://github.com/jkitchin/org-ref/issues/388

Click on this, and press "g". It should get the bibtex entry from the doi.

doi:10.1016/j.calphad.2017.01.009
* 399
github-issue:399

This is a natbib type, and if you do not use the natbib package, it will not work correctly in pdf export.

citenum:akhade-2011-effec
#+latex_class: article-nodefaults
#+latex_header: \usepackage{biblatex}
#+latex_header: \addbibresource{org-ref.bib}


* 356
  :PROPERTIES:
  :CUSTOM_ID:       8E93EBF7-D0D3-4024-B005-45729C6AC6E0
  :END:

cite:jkitchin76:online


printbibliography:nil


#+BEGIN_SRC emacs-lisp
(org-ref-get-html-bibliography)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(org-ref-get-bibtex-keys)
#+END_SRC

#+RESULTS:
| jkitchin76:online |


#+BEGIN_SRC emacs-lisp
(org-ref-find-bibliography)
#+END_SRC

#+RESULTS:
| org-ref.bib |


#+BEGIN_SRC emacs-lisp
(org-ref-get-bibtex-entry-html "jkitchin76:online")
#+END_SRC

#+BEGIN_SRC emacs-lisp
(org-ref-get-bibtex-entry-citation "jkitchin76:online")
#+END_SRC


#+BEGIN_SRC emacs-lisp
(bibtex-set-dialect 'biblatex)
(org-ref-key-in-file-p "jkitchin76:online" (file-truename "org-ref.bib"))
#+END_SRC

#+RESULTS:
: 9765
ref:8E93EBF7-D0D3-4024-B005-45729C6AC6E0e

* 405

ref:test-table

  #+name: test-table
  | 5 | 6 |
