# -*- org-edit-src-content-indentation: 0; -*-
#+TITLE: org-ref: citations, cross-references, indexes, glossaries and bibtex utilities for org-mode

#+BEGIN_HTML
<a href="https://travis-ci.org/jkitchin/org-ref"><img src="https://travis-ci.org/jkitchin/org-ref.svg?branch=master"></a>
#+END_HTML

See http://www.youtube.com/watch?v=Zya8SfmCtFA and https://www.youtube.com/watch?v=JyvpSVl4_dg for examples of org-ref in action.

[[./org-ref.org]] contains all documentation and installation instructions.


* Installation
** Installation via github
Clone this repo, add it to your load-path, and require org-ref. If you want the more stable branch, checkout the melpa branch. If you stay on master, you live on the bleeding edge with me ;)

** Package installation

The melpa branch of this repo is installable as an Emacs package.

You can add this to your init files to access our repo.

#+BEGIN_SRC emacs-lisp
(add-to-list package-archives
	     ("kitchingroup" . "https://raw.githubusercontent.com/jkitchin/melpa/kitchingroup/packages/") t)
#+END_SRC

Then, you should be able to do M-x package-list-packages, find org-ref and install it.

** Configuration
You should set these variables. Here is an example of how mine are set in an init.el file.
#+BEGIN_SRC emacs-lisp
(setq reftex-default-bibliography '("~/Dropbox/bibliography/references.bib"))

;; see org-ref for use of these variables
(setq org-ref-bibliography-notes "~/Dropbox/bibliography/notes.org"
      org-ref-default-bibliography '("~/Dropbox/bibliography/references.bib")
      org-ref-pdf-directory "~/Dropbox/bibliography/bibtex-pdfs/")

(setq helm-bibtex-bibliography "~/Dropbox/bibliography/references.bib")
(setq helm-bibtex-library-path "~/Dropbox/bibliography/bibtex-pdfs")

;; open pdf with system pdf viewer (works on mac)
(setq helm-bibtex-pdf-open-function
  (lambda (fpath)
    (start-process "open" "*open*" "open" fpath)))

;; alternative
;; (setq helm-bibtex-pdf-open-function 'org-open-file)

(setq helm-bibtex-notes-path "~/Dropbox/bibliography/helm-bibtex-notes")
#+END_SRC
You may want to set some convenient keys for working in your bibtex file. These commands operate on the citation key at point.

#+BEGIN_SRC emacs-lisp
(global-set-key [f10] 'org-ref-open-bibtex-notes)
(global-set-key [f11] 'org-ref-open-bibtex-pdf)
(global-set-key [f12] 'org-ref-open-in-browser)
#+END_SRC

Add this to your init.el files.
#+BEGIN_SRC emacs-lisp
(require 'org-ref)
#+END_SRC

Go forth and citate.

* Some other useful libraries in org-ref
Note many of these have been renamed with an org-ref prefix.

- [[./doi-utils.el][doi-utils]]
- [[./jmax-bibtex.el][jmax-bibtex]]
- [[./org-ref-arxiv.el][org-ref-arxiv]]
- [[./org-ref-pubmed.el][org-ref-pubmed]]
- [[./nist-webbook.el][nist-webbook]]
- [[./org-ref-wos.el][org-ref-wos]]
- [[./org-ref-isbn.el][org-ref-isbn]]
- [[./org-ref-scifinder.el][org-ref-scifinder]]
- [[./org-ref-isbn.el][org-ref-isbn]]
- [[./org-ref-scopus.el][org-ref-scopus]]
- [[./org-ref-worldcat.el][org-ref-worldcat]]
- [[./x2bib.el][x2bib]]

* Errors and issues
Please report errors here:  [[https://github.com/jkitchin/org-ref/issues][issue]]s.

* Contributors
I would like to thank the [[https://github.com/jkitchin/org-ref/graphs/contributors][contributors]] to org-ref, and everyone who has filed an [[https://github.com/jkitchin/org-ref/issues][issue]], or asked about org-ref on the [[http://orgmode.org/community.html][org-mode Mailing list]].
